apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-dns-server
  annotations:
    field.cattle.io/description: harvester-dns-server deployment
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        svc: harvester-qa-dns-server
        workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server
      namespace: default
    spec:
      affinity: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
      - name: harvester-cunnie-dns
        image: cunnie/sslip.io-dns-server:4.0.0
        args:
        - -nameservers
        - harvester-internal-hal.io
        resources:
        requests:
            cpu: 200m
            memory: 200Mi
        limits:
            cpu: 400m
            memory: 400Mi
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
    field.cattle.io/description: ipam lb harvester-dns-server
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: harvester-dns-server-lb
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ngx1lb
      nodePort: 30053
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    svc: harvester-qa-dns-server
  sessionAffinity: None
  type: LoadBalancer
---