apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-dns-server-airgap
  annotations:
    field.cattle.io/description: harvester-dns-server-airgap deployment
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server-airgap
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server-airgap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        svc: harvester-qa-dns-server-airgap
        workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-dns-server-airgap
      namespace: default
    spec:
      affinity: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
      - name: harvester-cunnie-dns
        image: cunnie/sslip.io-dns-server:4.0.0
        args:
        - -nameservers
        - harvester-internal-hal.io
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
    field.cattle.io/description: ipam lb harvester-dns-server-airgap
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: harvester-dns-server-lb-airgap
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dnsserverlbairgap
    nodePort: 30003
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    svc: harvester-qa-dns-server-airgap
  sessionAffinity: None
  type: LoadBalancer
---

