---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
    field.cattle.io/description: ipam lb harvester-nfs-server
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: harvester-nfs-server-lb
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nfsserverhvstr
      nodePort: 30049
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: nfsserverhvstrudp
      nodePort: 30111
      port: 111
      protocol: UDP
      targetPort: 111
  selector:
    svc: harvester-nfs-server
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-nfs-server
  namespace: default
  annotations:
    field.cattle.io/description: harvester-nfs-server deployment
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-nfs-server
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
  matchLabels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-nfs-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        svc: harvester-nfs-server
        workload.user.cattle.io/workloadselector: apps.deployment-default-harvester-nfs-server
        namespace: default
    spec:
        affinity: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        progressDeadlineSeconds: 600
        containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          env:
          - name: SHARED_DIRECTORY
            value: "/exports"
          volumeMounts:
          - mountPath: /exports
            name: nfs-vol
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          stdin: true
          tty: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
          privileged: true
          runAsNonRoot: false
          ports:
          - name: tcp-2049
            containerPort: 2049
            protocol: TCP
          - name: udp-111
            containerPort: 111
            protocol: UDP
        volumes:
        - name: nfs-vol
          persistentVolumeClaim:
          claimName: nfs-server-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/description: nfs-volume
    volume.beta.kubernetes.io/storage-provisioner: driver.harvesterhci.io
    volume.kubernetes.io/storage-provisioner: driver.harvesterhci.io
  name: nfs-server-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: harvester
  volumeMode: Filesystem
---
